"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Search, ArrowRight, CornerDownLeft } from "lucide-react";

type Result = {
  title: string;
  href: string;
  section: string;
  body: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let pf: any = null;
async function getPagefind() {
  if (!pf) {
    // Use new Function so bundlers don't try to resolve this at build time.
    // The file is generated by Pagefind after `npm run build`.
    const load = new Function("path", "return import(path)");
    pf = await load("/pagefind/pagefind.js");
    await pf.init();
  }
  return pf;
}

interface Props {
  onClose: () => void;
}

export default function SearchModal({ onClose }: Props) {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLUListElement>(null);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<Result[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);

  useEffect(() => { setSelectedIndex(0); }, [results]);
  useEffect(() => { inputRef.current?.focus(); }, []);

  useEffect(() => {
    if (!query.trim()) { setResults([]); return; }
    let cancelled = false;
    (async () => {
      try {
        const pagefind = await getPagefind();
        const search = await pagefind.search(query);
        if (cancelled) return;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const pages = await Promise.all(search.results.slice(0, 5).map((r: any) => r.data()));
        if (cancelled) return;
        const flat: Result[] = [];
        for (const page of pages) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          for (const sub of (page.sub_results ?? []) as any[]) {
            flat.push({
              section: page.meta?.title ?? "",
              title: sub.title,
              href: sub.url,
              body: sub.excerpt.replace(/<[^>]+>/g, ""),
            });
          }
        }
        setResults(flat.slice(0, 8));
      } catch {
        setResults([]);
      }
    })();
    return () => { cancelled = true; };
  }, [query]);

  function navigate(entry: Result) {
    router.push(entry.href);
    onClose();
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSelectedIndex((i) => Math.min(i + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSelectedIndex((i) => Math.max(i - 1, 0));
    } else if (e.key === "Enter" && results[selectedIndex]) {
      navigate(results[selectedIndex]);
    } else if (e.key === "Escape") {
      onClose();
    }
  }

  useEffect(() => {
    if (listRef.current) {
      const active = listRef.current.children[selectedIndex] as HTMLElement | undefined;
      active?.scrollIntoView({ block: "nearest" });
    }
  }, [selectedIndex]);

  return (
    <div
      className="fixed inset-0 z-[100] flex items-start justify-center px-4 pt-[18vh] bg-black/70 backdrop-blur-sm"
      onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="w-full max-w-lg rounded-xl border border-white/15 bg-zinc-900 shadow-2xl overflow-hidden"
        onKeyDown={handleKeyDown}
      >
        {/* Input */}
        <div className="flex items-center gap-3 border-b border-white/10 px-4 py-3">
          <Search className="h-5 w-5 shrink-0 text-white/40" aria-hidden="true" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search docs..."
            className="flex-1 bg-transparent text-white placeholder-white/35 outline-none text-sm"
          />
          <kbd className="rounded border border-white/15 px-1.5 py-0.5 text-xs text-white/35">Esc</kbd>
        </div>

        {/* Results */}
        {results.length > 0 ? (
          <ul ref={listRef} className="max-h-[60vh] overflow-y-auto py-1">
            {results.map((entry, i) => (
              <li key={entry.href}>
                <button
                  type="button"
                  onClick={() => navigate(entry)}
                  onMouseEnter={() => setSelectedIndex(i)}
                  className={`w-full flex items-start gap-3 px-4 py-3 text-left transition-colors ${
                    i === selectedIndex ? "bg-white/8" : "hover:bg-white/5"
                  }`}
                >
                  <Search className="mt-0.5 h-4 w-4 shrink-0 text-white/25" />
                  <div className="flex-1 min-w-0">
                    <p className="mb-0.5 text-[10px] font-medium uppercase tracking-[0.12em] text-white/35">
                      {entry.section}
                    </p>
                    <p className="text-sm font-medium text-white/90">{entry.title}</p>
                    <p className="mt-0.5 text-xs text-white/40 truncate">{entry.body}</p>
                  </div>
                  {i === selectedIndex && (
                    <CornerDownLeft className="mt-1 h-3.5 w-3.5 shrink-0 text-white/30" />
                  )}
                </button>
              </li>
            ))}
          </ul>
        ) : query ? (
          <div className="px-4 py-10 text-center text-sm text-white/35">
            No results for &ldquo;{query}&rdquo;
          </div>
        ) : (
          <div className="flex flex-col items-center gap-3 px-4 py-10 text-center text-sm text-white/35">
            <ArrowRight className="h-5 w-5 text-white/20" />
            Start typing to search docs
          </div>
        )}

        {/* Footer hint */}
        {results.length > 0 && (
          <div className="flex items-center gap-4 border-t border-white/8 px-4 py-2.5 text-[11px] text-white/25">
            <span className="flex items-center gap-1.5"><kbd className="rounded border border-white/15 px-1 py-0.5">↑</kbd><kbd className="rounded border border-white/15 px-1 py-0.5">↓</kbd> navigate</span>
            <span className="flex items-center gap-1.5"><kbd className="rounded border border-white/15 px-1 py-0.5">↵</kbd> open</span>
            <span className="flex items-center gap-1.5"><kbd className="rounded border border-white/15 px-1 py-0.5">Esc</kbd> close</span>
          </div>
        )}
      </div>
    </div>
  );
}
